### ISSUE TITLE
Unable to build with makefile

### ISSUE THREAD

**Issue by DevManu-de** [TinyKern/TinyKernel#6]
**Describe the bug**
I cloned this repo with `git clone https://github.com/TinyKern/TinyKernel.git` and then tried to compile it by typing `make` as described in the README.md and then I got following linker error
```
CC src/sys/char.c -> build/obj/src/sys/char.c.o
CC src/sys/utils.c -> build/obj/src/sys/utils.c.o
CC src/drivers/keyboard/keyboard.c -> build/obj/src/drivers/keyboard/keyboard.c.o
CC src/drivers/vga/vga.c -> build/obj/src/drivers/vga/vga.c.o
AS src/bootloader/boot.s -> build/obj/src/bootloader/boot.s.o
CC src/kernel/stdio.c -> build/obj/src/kernel/stdio.c.o
src/kernel/stdio.c: In function ‘__kprintf’:
src/kernel/stdio.c:60:15: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
   60 |         if (i < 0)
      |               ^
CC src/kernel/cpu/ports.c -> build/obj/src/kernel/cpu/ports.c.o
CC src/kernel/kernel.c -> build/obj/src/kernel/kernel.c.o
CC src/kernel/errno.c -> build/obj/src/kernel/errno.c.o
\nLinking -> build/boot/TinyKernel.bin
ld: build/obj/src/kernel/stdio.c.o: in function `.L19':
stdio.c:(.text+0x304): undefined reference to `__stack_chk_fail_local'
ld: build/obj/src/kernel/errno.c.o: in function `kprint_error':
errno.c:(.text+0xe6): undefined reference to `__stack_chk_fail_local'
ld: build/obj/src/kernel/errno.c.o: in function `kpanic':
errno.c:(.text+0x176): undefined reference to `__stack_chk_fail_local'
ld: build/boot/TinyKernel.bin: hidden symbol `__stack_chk_fail_local' isn't defined
ld: final link failed: bad value
make: *** [Makefile:60: build/boot/TinyKernel.bin] Error 1

```
I am trying to build this on Arco Linux with Kernel: `5.12.15-zen1-1-zen` and gcc: `11.1.0` and linker: `2.36.1`

**To Reproduce**
1. clone the repo
2. type `make`
3. See error

**Expected behavior**
Successfull compilation

**Desktop (please complete the following information):**
 - OS: `Arco Linux, Kernel 5.12.15-zen1-1-zen`

**Comment by bobrossrtx** [comment]
I am developing this in Ubuntu~20.04 and using GCC~9.3 I will try building with GCC~11.1 then I will try building on Arch. I will share my result soon.

**Comment by bobrossrtx** [comment]
From what I have read, it appears that you might not be using the same version of libc, this is most likely where the architectures between Arch & Debian are very much different. The main issue here is most likely the "stdarg.h" file, which is to be implemented as its own instead of using the official libc version. This will be implemented, but I will also check the gcc version and see if that has any issues. But since this is a linker error, and it gives an undefined reference, I suspect that is down to libc. You can try point the linker to the libc version inside of the Makefile, but that is something that I can't really test at the moment.

**Comment by DevManu-de** [comment]
My current version of glibc is `2.33-5`

**Comment by bobrossrtx** [comment]
It seems that it might be an issue with compiling the source code to the object files, it works perfectly on Debian-based distros. you could possibly try using an earlier GCC version, I use GCC-9.3.0, but other than that, I'm really stuck on this issue, I've been working on it all day, and it's really bugging me. I'm afraid I won't be working on it for the next few days though since I will be away for a little bit. (I will stay active inside of GitHub issues)

**Comment by bobrossrtx** [comment]
I also don't think that it is the kernel version you are using, but I use `5.8.0-59-generic` on Ubuntu-`20.04` if that is any insight into the issue.

**Comment by bobrossrtx** [comment]
I may have fixed the problem for this issue inside of the `Makefile`, if there are still any problems, please re-open this issue or open a new one

**Comment by DevManu-de** [comment]
This actually solved the linking issue but `mcopy` from `grub-mkrescue` fails.
```
CC src/sys/char.c -> build/obj/src/sys/char.c.o
CC src/sys/utils.c -> build/obj/src/sys/utils.c.o
CC src/drivers/keyboard/keyboard.c -> build/obj/src/drivers/keyboard/keyboard.c.o
CC src/drivers/vga/vga.c -> build/obj/src/drivers/vga/vga.c.o
AS src/bootloader/boot.s -> build/obj/src/bootloader/boot.s.o
CC src/kernel/stdio.c -> build/obj/src/kernel/stdio.c.o
src/kernel/stdio.c: In function ‘__kprintf’:
src/kernel/stdio.c:60:15: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
   60 |         if (i < 0)
      |               ^
CC src/kernel/cpu/ports.c -> build/obj/src/kernel/cpu/ports.c.o
CC src/kernel/kernel.c -> build/obj/src/kernel/kernel.c.o
CC src/kernel/errno.c -> build/obj/src/kernel/errno.c.o
\nLinking -> build/boot/TinyKernel.bin
mcopy: No directory slots
grub-mkrescue: error: `mcopy` invocation failed
.
make: *** [Makefile:52: iso] Error 1

```
